name: "Auto Request Changes"
description: "Automatically request changes pull requests"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  github-token:
    description: "The Github token. By default, it will using GITHUB_TOKEN to use the repo token."
    required: true
  comment-body:
    description: "The comment body to create a request changes review. The default is `Some actions are not successful, please fix it.`."
    default: "Some actions are not successful, please fix it."
    required: false
  pull-request-number:
    description: "(optional) The ID of a pull request to auto-request-changes. By default, this action tries to use the pull_request event payload."
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
